spring.application.name=freshbasket
spring.datasource.url=jdbc:postgresql://localhost:5432/fresh_basket
spring.datasource.username=postgres
spring.datasource.password=Alex123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.main.allow-bean-definition-overriding=true
#acceso temporal a las apis 
spring.security.user.name=admin
spring.security.user.password=Alex123